/* Copyright (C) 2018 BMW Group
 * Author: Bernhard Hennlich (bernhard.hennlich@bmw.de)
 * This Source Code Form is subject to the terms of the Eclipse Public
 * License, v. 1.0. If a copy of the EPL was not distributed with this
 * file, You can obtain one at https://www.eclipse.org/legal/epl-v10.html.
 */
package org.franca.compmodel.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.franca.compmodel.dsl.fcomp.FCModel
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(FCompInjectorProvider)


// Example Test Generated by Xtext
class FCompParsingTest {
	@Inject
	ParseHelper<FCModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			package org.example
			
			component Component {
				version { major 1 minor 0 }
			}
			
			device HelloServerECU { 
				adapter EthernetCard1
				adapter EthernetCard2
				adapter CAN_TX_1
			}
			
			device HelloClientECU {
				device Core_1
				adapter EthernetCard
			}
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
